apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 038445823716.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 038445823716.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: 9f8ca690
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
